import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { generateMealPlan } from "@/lib/rotation-algorithm";
import type { Recipe, MealPlanItem, MealType } from "@/types/database";

// ---------------------------------------------------------------------------
// POST /api/meal-plan/generate
// ---------------------------------------------------------------------------

export async function POST(request: Request) {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
    }

    // Parse request body
    const body = await request.json();
    const { mealPlanId, weekStart } = body as {
      mealPlanId: string;
      weekStart: string;
    };

    if (!mealPlanId || !weekStart) {
      return NextResponse.json(
        { error: "mealPlanId and weekStart are required" },
        { status: 400 }
      );
    }

    // Verify the meal plan belongs to this user
    const { data: mealPlan, error: planError } = await supabase
      .from("meal_plans")
      .select("*")
      .eq("id", mealPlanId)
      .eq("user_id", user.id)
      .single();

    if (planError || !mealPlan) {
      return NextResponse.json(
        { error: "Meal plan not found" },
        { status: 404 }
      );
    }

    // Fetch user's profile to get meal_slots
    const { data: profile, error: profileError } = await supabase
      .from("profiles")
      .select("meal_slots")
      .eq("user_id", user.id)
      .single();

    if (profileError || !profile) {
      return NextResponse.json(
        { error: "Profile not found. Please set up your meal preferences." },
        { status: 404 }
      );
    }

    const mealSlots: MealType[] = profile.meal_slots ?? [
      "breakfast",
      "lunch",
      "dinner",
    ];

    // Fetch all user recipes
    const { data: recipes, error: recipesError } = await supabase
      .from("recipes")
      .select("*")
      .eq("user_id", user.id);

    if (recipesError) {
      return NextResponse.json(
        { error: recipesError.message },
        { status: 500 }
      );
    }

    if (!recipes || recipes.length === 0) {
      return NextResponse.json(
        { error: "No recipes found. Add some recipes before generating a meal plan." },
        { status: 400 }
      );
    }

    // Fetch current meal plan items (manually placed ones are kept;
    // auto-generated ones are cleared and re-generated)
    const { data: existingItems, error: existingError } = await supabase
      .from("meal_plan_items")
      .select("*")
      .eq("meal_plan_id", mealPlanId);

    if (existingError) {
      return NextResponse.json(
        { error: existingError.message },
        { status: 500 }
      );
    }

    // Separate manually-placed items (have custom_name or were not auto-generated)
    // from auto-generated items. Items with a custom_name are always manual.
    // Items with only a recipe_id and no custom_name are considered auto-generated
    // and will be replaced.
    const manualItems = (existingItems ?? []).filter(
      (item) => item.custom_name !== null
    );
    const autoGeneratedIds = (existingItems ?? [])
      .filter((item) => item.custom_name === null)
      .map((item) => item.id);

    // Delete existing auto-generated items
    if (autoGeneratedIds.length > 0) {
      const { error: deleteError } = await supabase
        .from("meal_plan_items")
        .delete()
        .in("id", autoGeneratedIds);

      if (deleteError) {
        return NextResponse.json(
          { error: deleteError.message },
          { status: 500 }
        );
      }
    }

    // Run the rotation algorithm
    // Pass manual items as "existing" so the algorithm respects occupied slots
    const assignments = generateMealPlan(
      recipes as Recipe[],
      mealSlots,
      manualItems as MealPlanItem[]
    );

    if (assignments.length === 0) {
      return NextResponse.json({ data: [] });
    }

    // Insert the generated items
    const insertRows = assignments.map((a) => ({
      meal_plan_id: mealPlanId,
      day_of_week: a.day_of_week,
      meal_slot: a.meal_slot,
      recipe_id: a.recipe_id,
      custom_name: null,
    }));

    const { data: insertedItems, error: insertError } = await supabase
      .from("meal_plan_items")
      .insert(insertRows)
      .select("*, recipe:recipes(*)");

    if (insertError) {
      return NextResponse.json(
        { error: insertError.message },
        { status: 500 }
      );
    }

    return NextResponse.json({ data: insertedItems });
  } catch (err) {
    console.error("Error generating meal plan:", err);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
